[versions]
agp = "9.1.1"
coreKtx = "1.16.0"
lifecycleRuntimeKtx = "2.8.4"
junit = "4.13.2"
jsch = "0.2.17"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
jsch = { group = "com.github.mwiede", name = "jsch", version.ref = "jsch" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }